services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.5
    container_name: keycloak
    command: start-dev

    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    volumes:
      - keycloak_data:/opt/keycloak/data
    ports:
      - "9090:8080"

    restart: unless-stopped
volumes:
  keycloak_data: